RTO_CITY_MAP = {
    "NEW": "New",
    "TEMP": "Temporary",
    # Western UP (Codes UP-11 to UP-27)
    "UP11": "Saharanpur",
    "UP12": "Muzaffarnagar",
    "UP13": "Bulandshahr",
    "UP14": "Ghaziabad",
    "UP15": "Meerut",
    "UP16": "Noida",
    "UP17": "Baghpat",
    "UP18": "Greater Noida",
    "UP19": "Shamli",
    "UP20": "Bijnor",
    "UP21": "Moradabad",
    "UP22": "Rampur",
    "UP23": "Amroha",
    "UP24": "Badaun",
    "UP25": "Bareilly",
    "UP26": "Pilibhit",
    "UP27": "Shahjahanpur",
    "UP28": "Faizabad",
    "UP29": "Yusufpur",
    # Central & Lucknow Region (Codes UP-30 to UP-39)
    "UP30": "Hardoi",
    "UP31": "Lakhimpur Kheri",
    "UP32": "Lucknow",
    "UP33": "Raebareli",
    "UP34": "Sitapur",
    "UP35": "Unnao",
    "UP36": "Amethi",
    "UP37": "Hapur",
    "UP38": "Sambhal",
    # Eastern UP (Codes UP-40 to UP-58)
    "UP40": "Bahraich",
    "UP41": "Barabanki",
    "UP42": "Ayodhya",
    "UP43": "Gonda",
    "UP44": "Sultanpur",
    "UP45": "Akbarpur",
    "UP46": "Shravasti",
    "UP47": "Balrampur",
    "UP50": "Azamgarh",
    "UP51": "Basti",
    "UP52": "Deoria",
    "UP53": "Gorakhpur",
    "UP54": "Mau",
    "UP55": "Siddharthnagar",
    "UP56": "Maharajganj",
    "UP57": "Padrauna",
    "UP58": "Sant Kabir Nagar",
    # Central & Bundelkhand (Codes UP-60 to UP-96)
    "UP60": "Ballia",
    "UP61": "Ghazipur",
    "UP62": "Jaunpur",
    "UP63": "Mirzapur",
    "UP64": "Sonbhadra",
    "UP65": "Varanasi",
    "UP66": "Bhadohi",
    "UP67": "Chandauli",
    "UP70": "Prayagraj",
    "UP71": "Fatehpur",
    "UP72": "Pratapgarh",
    "UP73": "Kaushambi",
    "UP74": "Kannauj",
    "UP75": "Etawah",
    "UP76": "Farrukhabad",
    "UP77": "Kanpur Dehat",
    "UP78": "Kanpur",
    "UP79": "Auraiya",
    "UP80": "Agra",
    "UP81": "Aligarh",
    "UP82": "Etah",
    "UP83": "Firozabad",
    "UP84": "Mainpuri",
    "UP85": "Mathura",
    "UP86": "Hathras",
    "UP87": "Kasganj",
    "UP90": "Banda",
    "UP91": "Hamirpur",
    "UP92": "Jalaun",
    "UP93": "Jhansi",
    "UP94": "Lalitpur",
    "UP95": "Mahoba",
    "UP96": "Chitrakoot",
}
